language: php

php:
  - '7.4'
  - '8.0'
  - '8.1'

env:
  global:
    CI: 'true'
    TEST_OUTPUT_STYLE: 'pretty'
    PHPCS_REPORT_STYLE: 'full'
    COMPOSER_OPTIONS: '--optimize-autoloader'

sudo: false

matrix:
  fast_finish: true

before_install:
  # remove xdebug to speed up build
  - phpenv config-rm xdebug.ini || true

install:
  - make build
script:
  - make test-technical
  - make test-functional

cache:
  directories:
    - $HOME/.composer
    - vendor

branches:
  except:
  - /.*\-dev$/
  - /.*\-patch(\-\d+)?$/
