name: 'CI'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [ master ]

concurrency:
  group: "CI-${{ github.head_ref }}"
  cancel-in-progress: true

env:
  # Cache params
  CACHE_VERSION: 2022031802 # To be able to create a new cache (YYYYMMDDXX)
  CI: 'true'
  COVERAGE_OUTPUT_STYLE: clover
  TEST_OUTPUT_STYLE: 'pretty'
  PHPCS_REPORT_STYLE: 'full'
  COMPOSER_OPTIONS: '--optimize-autoloader'

jobs:
  unit-tests:
    name: Unit / PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          tools: composer
          coverage: xdebug
        env:
          # Always use latest available patch for the version
          update: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer
            ./vendor
          # Clear the cache if composer json (as composer.lock is in the repo) has been updated
          key: ${{ env.CACHE_VERSION }}-tests-${{ matrix.php-version }}-${{ hashFiles('composer.json') }}

      - name: Build
        run: make build

      - name: Test
        run: make test-unit

      - name: Code style
        if: matrix.php-version == '7.4'
        run: make codestyle

      # See the reports at https://codecov.io/gh/yoanm/php-jsonrpc-doc-sdk
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          name: "unit-tests-${{ matrix.php-version }}"
          flags: "unit-tests,php-${{ matrix.php-version }}"
          fail_ci_if_error: true

      - name: Upload coverage to scrutinizer
        run: php vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage/clover.xml

  functional-tests:
    name: Functional / PHP ${{ matrix.php-version }}
    needs: [unit-tests]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          tools: composer
          coverage: xdebug
        env:
          # Always use latest available patch for the version
          update: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer
            ./vendor
          # Clear the cache if composer json (as composer.lock is in the repo) has been updated
          key: ${{ env.CACHE_VERSION }}-tests-${{ matrix.php-version }}-${{ hashFiles('composer.json') }}

      - name: Build
        run: make build

      - name: Test
        run: make test-functional

      # See the reports at https://codecov.io/gh/yoanm/php-jsonrpc-doc-sdk
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          name: "functional-tests-${{ matrix.php-version }}"
          flags: "functional-tests,php-${{ matrix.php-version }}"
          fail_ci_if_error: true

      - name: Upload coverage to scrutinizer
        run: php vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage/clover.xml
